# Generated by Django 2.1.7 on 2019-04-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fname',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lname',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
