# Generated by Django 2.1.7 on 2019-04-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190402_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fname',
            field=models.CharField(default='firstname', max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lname',
            field=models.CharField(default='lastname', max_length=25),
        ),
    ]
