# Generated by Django 2.1.7 on 2019-04-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190402_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='student status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='teacher status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fname',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lname',
            field=models.CharField(default='', max_length=25),
        ),
    ]
