# Generated by Django 2.1.7 on 2019-04-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
