# Generated by Django 2.1.7 on 2019-04-02 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190402_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher_id',
        ),
    ]
