# Generated by Django 2.1.7 on 2019-04-02 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_student_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teacher_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Teacher'),
        ),
    ]
