# Generated by Django 2.1.7 on 2019-04-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_student_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_xp',
            field=models.IntegerField(default=0),
        ),
    ]
