# Generated by Django 2.1.7 on 2019-04-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_gameinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinstance',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
